---
jobs:
- name: embed
  public: true
  plan:
  - aggregate:
    - get: boshrelease
      trigger: false
    - get: resource-image
      passed: [resource-image]
      params: {rootfs: true}
      trigger: false
  - task: embed-image-blob
    config:
      platform: linux
      image: docker:///concourse/concourse-ci
      inputs:
      - {name: boshrelease, path: .}
      - {name: resource-image}
      run:
        path: ./src/ci/scripts/embed_image_blob.sh
        args: [resource-image, bosh-errand-resource]
      params:
        access_key_id: {{aws-access-key-id}}
        secret_access_key: {{aws-secret-access-key}}
  - put: boshrelease
    params:
      repository: embed-image-blob
      rebase: true

- name: resource-image
  public: true
  plan:
  - get: bosh-errand-resource
    trigger: true
  - put: resource-image
    params:
      build: bosh-errand-resource

resources:
- name: bosh-errand-resource
  type: git
  source:
    uri: https://github.com/starkandwayne/bosh-errand-resource.git
    branch: master

- name: boshrelease
  type: git
  source:
    uri: git@github.com:starkandwayne/bosh-errand-resource-boshrelease.git
    branch: master
    private_key: {{github-private-key}}

- name: resource-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: clutteredraisins/bosh-errand-resource
